apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels: 
    app: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      resources: 
        limits:
          memory: "256Mi"
          cpu: "400m"
      ports:
        - containerPort: 80

